public enum TURN_STATE { DAY, NIGHT, END };

public enum DIRECTION { LEFT, UP, DOWN, RIGHT, EVERYWHERE };

public enum AI_STATE { IDLE, MOVE, ATTACK, EATEN, DISABLED, GROGGY, END };

public enum AI_WORLD_STATE { CAMP, MOVE, END };

public enum ENEMY_TYPE { LIVESTOCK, CIVILIAN, MERCENARY, KNIGHT, HERO, END};

public enum MOUSE_STATE { NORMAL, HEAL, END };

public enum PART_TYPE { HEAD, BODY, ARM, LEG, END };

public enum WORLDICON_TYPE { EMPTY, FARM, RANCH, VILLAGE, CITY, CASTLE, END };

public enum WORLDTURN_STATE { IDLE, MOVE, END };

public enum WORLD_GEO { GRASS, WATER, END };

public enum PARTY_TYPE { CARAVAN, RAID, END };

public enum HERO { WALLACE, END };