public enum TURN_STATE { DAY, NIGHT, END };

public enum DIRECTION { LEFT, UP, DOWN, RIGHT, EVERYWHERE };

public enum AREA_STATE { FOREST, FARM, VILLAGE, CASTLE };

public enum VICTIM { CATTLE, KNIGHT, WOLF, NONE };

public enum AI_STATE { IDLE, MOVE, ATTACK, EATEN, END };
