public enum TURN_STATE { USER_MOVE, USER_ATTACK, ENEMY_MOVE, ENEMY_ATTACK , ASSEMBLE, END };

public enum DIRECTION { LEFT, UP, DOWN, RIGHT, EVERYWHERE };

public enum AREA_STATE { FOREST, FARM, VILLAGE, CASTLE };

public enum VICTIM { PIG, KNIGHT, NONE };